=== cloudblue/connect-extension-mulesoft/src/test/resources/ProductActionList-schema.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type" : "object",
    "properties" : {
      "action" : {
        "type" : "string"
      },
      "description" : {
        "type" : "string"
      },
      "events" : {
        "type" : "object",
        "properties" : {
          "created" : {
            "type" : "object",
            "properties" : {
              "at" : {
                "type" : "string"
              },
              "by" : {
                "type" : "object",
                "properties" : {
                  "id" : {
                    "type" : "string"
                  },
                  "name" : {
                    "type" : "string"
                  }
                }
              }
            }
          },
          "updated" : {
            "type" : "object",
            "properties" : {
              "at" : {
                "type" : "string"
              },
              "by" : {
                "type" : "object",
                "properties" : {
                  "id" : {
                    "type" : "string"
                  },
                  "name" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        }
      },
      "id" : {
        "type" : "string"
      },
      "name" : {
        "type" : "string"
      },
      "scope" : {
        "type" : "string",
        "enum" : [ "asset", "tier1", "tier2" ]
      },
      "title" : {
        "type" : "string"
      },
      "type" : {
        "type" : "string",
        "const" : "button"
      }
    }
  }
}

=== cloudblue/connect-extension-mulesoft/src/test/resources/__files/product_actions.json
[
  {
    "action": "sso_action",
    "name": "Sign In",
    "type": "button",
    "scope": "asset",
    "description": "Sign in into the service by clicking at this button",
    "id": "ACT-000-000-001",
    "events": {
      "created": {
        "at": "2020-08-21T09:26:23+00:00"
      },
      "updated": {
        "at": "2020-08-21T09:26:23+00:00"
      }
    },
    "title": "Sign In"
  }
]
